#import "index.typ": template
#show: template

= LLM (Large Language Model)

#table(
  columns: 2,
  [Steward], [Lachlan Kermode],
  [Editor], [Lachlan Kermode],
)


An LLM, or Large Language Model, is the name given to the kind of machine learning architecture that powers conversational interfaces like ChatGPT, Claude, and Gemini.

Why distinguish large language models from (regularly sized) language models?
The conventional wisdom is that the qualifier 'large' refers both to the enormous amount of text on which such systems are trained---which comprise hundreds of billions of words from books, websites, and other sources---and also to the massive number of parameters that they contain.
These parameters are sometimes represented as 'neurons' (see #link("neural-net.typ")[neural net]), as the original motivation for their technical mechanism was inspired by biological neurons @rosenblattPerceptronProbabilisticModel1958.

== Recent usage
The core neural net architecture of a 'language model', then, has been around since the 1960s.
But the acronym LLM only really entered the scientific and software engineering vocabulary in 2017, when the growing adoption of the #link("./transformer.typ")[transformer] architecture began to render the language generated by computational models intelligible and even insightful, at times. 
This is also, perhaps, why we distinguish large language models from language models: there is a widespread sense that they only began to 'work'---that is, generate language that was convincing in a new register than previous attempts--- once the architectures and training data both became large enough.

It became more common to toss around the terminology of LLMs in the layman's lexicon around late 2022, when ChatGPT was launched to the public, giving the transformer architecture a stage and a spotlight.
LLMs are to ChatGPT as search engines are to Google: though the latter term is actually a specific company's product, it has become a stand-in for the technical architecture that underlies it on account of being the main vector of that architecture's popularization.
In the 2020s, LLM is also the name of the machine learning architecture to which one typically refers when one speaks about '#link("./artificial-intelligence.typ")[AI]', a phraseology that tends to index the 'latest and greatest' technique in computing automation at any given historical moment.

In addition to the transformative experience of automatic language generation associated with ChatGPT, the architectural particulars of LLMs are also associated---though usually not entirely accurately---with several recent scientific and technical breakthroughs. 
The strong association that LLMs have to these breakthroughs give them an outsized gravitas in the current discourse on the social disruption that #link("./artificial-intelligence.typ")[AI] and #link("./artificial-general-intelligence.typ")[AGI] are augured to effect.
We limit ourselves to two of the most prominent applicative (mis)associations or, if you prefer, apparitions of LLMs here.

Google Deepmind's AlphaFold @jumperHighlyAccurateProtein2021a, a neural net that can predict protein folding structure with a level of accuracy not previously possible, is perhaps most important apparition of an LLM, as its developers were awarded the Nobel Prize for Chemistry in 2024 @callawayChemistryNobelGoes2024. 
  A case in point, AlphaFold's technical architecture is often glossed rather imprecisely as 'AI', and is often miscredited as an application of LLMs to the domain of scientific-qua-chemical data. 
  Though AlphaFold is a #link("./neural-net.typ")[neural net] that shares some architectural features with LLMs such as #link("./attention.typ")[attention], it does not operate over 'language' (represented as linear chains of #link("/tokenization.typ")[tokens]), and is therefore not _really_ a Large _Language_ Model. 

AI-generated images and video such as Stable Diffusion @rombachHighresolutionImageSynthesis2022 and OpenAI's SORA @liuSoraReviewBackground2024. Analogously to AlphaFold, Stable Diffusion shares architectural features such as #link("./attention.typ")[attention] with LLMs, but also employs techniques from computer vision research in the 2010s (the previous 'wave' of techniques temporarily dubbed '#link("./artificial-intelligence.typ")[artificial intelligence]') such as the UNet architecture @ronnebergerUNetConvolutionalNetworks2015, an approach originally designed to segment sections of images in biomedical applications. SORA, too, is not an LLM, but a recombination of architectural insights in #link("./neural-net.typ")[neural net] construction across various domains. It is the #link("./multimodality.typ")[multimodality] of these models---their ability to generate images or video from _textual_ prompts---that is probably what accounts for their common confusion with LLMs.

== Prehistory 

LLMs have provoked a general hysteria around how the automation of textual language's production could upend our societal and even existential situation.
Despite the persistent suggestion that we are dealing with an entirely novel technology, this species of hysteria has great precedent in the history of computer science.

In his now-famous 1950 paper, _Computing Intelligence and Machinery_ @turingComputingMachineryIntelligence2004, Alan Turing proposed the imitation game as a thought experiment which could frame advances in the nascent field of 'artificial intelligence'.
The imitation game, now colloquially known as the Turing test, comprises three agents. 
Two are in the same room, and one remains outside. 
The agent outside is required to nominate which one of the two agents in the room is a woman, and which one is a man: this is the 'test'.
To gather information, however, the agent outside may only send typewritten messages to the agents inside, and these inside agents have their own agendas.
The male agent is asked to pretend to be a woman, whereas the woman need only convince that she is really herself. 
The test is 'passed' when the outside agent can correctly guess the gender of the other two.
A computer has passed the test, in Turing's estimation, when it can play the part of the male agent (pretending to be a woman) effectively enough to fool a human outside agent.

Notwithstanding the strange (and often unremarked upon) gender politics of this setup, the possibility of passing the Turing test has steered artificial intelligence over the past 75 years. 
It is important to note that, far from being a scientifically sanctioned experiment which accurately proves or disproves 'intelligence', the Turing test is a game contrived to make it reasonable to measure a machine's capabilities in the same arena as a human's.
As to why the test restricts agential communication to typewritten messages; Turing reasons, as the deafblind #link("https://en.wikipedia.org/wiki/Helen_Keller")[Hellen Keller] is nevertheless clearly intelligent, the domain of intelligence should not require anything particularly corporeal other than (typewritten) language.#footnote[#quote[We need not be too concerned about the legs, eyes, etc. The example of Miss Helen Keller shows that education can take place provided that communication in both directions between teacher and pupil can take place by some other means. @turingComputingMachineryIntelligence2004[p.471]]]

[WIP] Add historical context via ELIZA and the general failure to produce convincing text pre-#link("./transformer.typ")[transformer]. The status of language in the Turing test and its restricted, 'type-written' domain.

== Extensions, prehensions, and pretensions

[IDEA] Leif Weatherby's argument regarding the structure(-alism) of language and the forfeiture of remainder humanism, ceding its epistemic terrain to the racketeer empiricism of cognitive science.

#bibliography("./references.bib")
